# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ioana/Desktop/scs/ALU/ALU.cache/wt [current_project]
set_property parent.project_path C:/Users/Ioana/Desktop/scs/ALU/ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Ioana/Desktop/scs/ALU/ALU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Ioana/Desktop/scs/FullAdd.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/half_adder.vhd
  C:/Users/Ioana/Desktop/scs/WALLACE/WALLACE.srcs/sources_1/new/add_2.vhd
  C:/Users/Ioana/Desktop/scs/DivisionOperation.vhd
  C:/Users/Ioana/project_6/project_6.srcs/sources_1/new/SSD.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/ShiftLeft.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/Riplle8.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/OR_GATE.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/NOT_GATE.vhd
  C:/Users/Ioana/project_6/project_6.srcs/sources_1/new/MPG.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/AND_GATE.vhd
  C:/Users/Ioana/Desktop/scs/division/division.srcs/sources_1/new/ACC.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/MultiplierComponent.vhd
  C:/Users/Ioana/Desktop/scs/ALU/ALU.srcs/sources_1/new/AluUnit.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Ioana/Desktop/Basys/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Ioana/Desktop/Basys/Basys3_Master.xdc]


synth_design -top AluUnit -part xc7a35tcpg236-1


write_checkpoint -force -noxdef AluUnit.dcp

catch { report_utilization -file AluUnit_utilization_synth.rpt -pb AluUnit_utilization_synth.pb }
